### PR TITLE
Issue 264

### LINKED ISSUE #126: [WCCMMUD] MajorMud - Crashes when attempting to SET SUICIDE password
**Module Information**
* Identifier: WCCMMUD
* Module Name: MajorMud
* Version: 1.11g

**Describe the bug**
After creating character, it asks you to SET SUICIDE (password), game crashes when trying to set

**To Reproduce**
1. Enter MajorMud module
2. Create character
3. Type "SET SUICIDE" to set suicide password
4. See Error

**Expected behavior**
Able to set suicide password

**Screenshots**
```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in MAJORBBS: 811')
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner

### LINKED ISSUE #264: [DIALCHAT] Dial Chat - Crash when changing color in chat
**Module Information**
* Identifier: DIALCHAT
* Module Name: DialChat
* Version: unknown 

**Describe the bug**
Crash when changing color in chat

**To Reproduce**
1. Enter DialChat module
2. Hit <TAB> to change chat color
3. See Error

**Expected behavior**
Able to chat in different ANSI colors

```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in GALGSBL: 62')
   at MBBSEmu.HostProcess.ExportedModules.Galgsbl.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Op_Call()
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows 2019 Server Standard
- Telnet Client: NetRunner
- MBBSEmu Build: 110720-2

### LINKED ISSUE #312: [LOGSAS] Swords & Sorcery - Crashes when trying to move
**Module Information**
* Identifier: LOGSAS
* Module Name: Swords & Sorcery
* Version: 1.24

**Describe the bug**
Crashes when trying to move

**To Reproduce**
1. Add module to moduleConfig.json
2. Load MBBSEmu
3. Enter Module
4. Create Character
5. Try to move 

**Expected behavior**
Ability to move rooms

**Screenshots**
```
2020-11-28 15:26:52.6647 Info MBBSEmu.HostProcess.ExportedModules.Galgsbl.btucmd Enable ANSI on channel 0 (Ignored)
2020-11-28 15:27:04.3706 Info MBBSEmu.HostProcess.ExportedModules.Galgsbl.btucmd Enable ANSI on channel 0 (Ignored)
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in GALGSBL: 62')
   at MBBSEmu.HostProcess.ExportedModules.Galgsbl.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Op_Call()
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows Server 2019 Core
- Telnet Client: NetRunner
- MBBSEmu Build: 112620-9

### PR DESCRIPTION
**Pull request by enusbaum**
- Implemented `MAJORBBS.881` (ECHESC)
- Implemented `GALGSBL.62` (CHIINP)
- Refactored Input & Echo Code, removing logic from `SessionBase` as well as Menu Handlers
- Simplified Input Chain of events for GSBL Input Events

Fixes #312 
Fixes #264 
Fixes #126

### CODE REVIEW

File: MBBSEmu/HostProcess/ExportedModules/Galgsbl.cs [hunk 1]
```diff
@@ -995,5 +999,26 @@ private void btuinp()
...
+
+            if (!ChannelDictionary.TryGetValue(channelNumber, out var channel))
+            {
+                Registers.AX = ERROR_CHANNEL_NOT_DEFINED;
+                return;
+            }
+
+            channel.InputBuffer.WriteByte(character);
+
+            _logger.Debug($"Adding {character:X2} to input buffer");
```
Comment (paladine) [inline MBBSEmu/HostProcess/ExportedModules/Galgsbl.cs:1021]: not necessary? With the tests we should have confidence that this works, thus reducing the need to verify via logs?

Or at least guard behind `#ifdef DEBUG`

**Review by paladine — APPROVED** [review]

**Review by paladine — APPROVED** [review]
