### PR TITLE
Fix for Multiple SPR's in a single call

### LINKED ISSUE #204: [WCCMMUD] MajorMud - Topten Adventurers does not show name
**Module Information**
* Identifier: WCCMMUD
* Module Name: MajorMud
* Version: 1.11g

**Describe the bug**
Topten Adventurers does not show name

**To Reproduce**
1. Enter MajorMud module
2. Select "T" Top Ten Adventurers
4. See Error

**Expected behavior**
Show names of adventurers

**Screenshots**
```
No Console Error
```

MMTOPTEN

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner
- MBBSEmu Build: 101820-1

### PR DESCRIPTION
**Pull request by enusbaum**
- SPR now uses a ring buffer of 4 pointers
- Cleaned up unused variables in `majorbbs.cs`
- Unit Tests for SPR scenarios

Fixes #204 

Screen Shot 2020-11-12 at 6 54 08 PM

### CODE REVIEW

File: MBBSEmu/HostProcess/ExportedModules/Majorbbs.cs [hunk 1]
```diff
@@ -2524,15 +2523,13 @@ private void spr()
             //If the supplied string has any control characters for formatting, process them
             var formattedMessage = FormatPrintf(output, 2);
 
-            if (formattedMessage.Length > 0x400)
+            if (formattedMessage.Length > 1024)
```
Comment (paladine) [inline MBBSEmu/HostProcess/ExportedModules/Majorbbs.cs:2526]: could probably lower this limit, but then again we're not overly concerned with memory usage at this point

**Review by paladine — APPROVED** [review]
