### PR TITLE
Fixed Issue #207

### LINKED ISSUE #207: [WCCMMUD] MajorMud - Reading a spell scroll crashes the system
**Module Information**
WCCMMUD 

**Describe the bug**
I created a Paladin, bought two spell scrolls. I read the first which seemed to work, though there was some sort of `prfmsg` shortening. The second scroll I read crashed the system

**To Reproduce**
See above

**Expected behavior**
I learn the spell.

```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MBBSEmu.Memory.MemoryCore.GetByte(UInt16 segment, UInt16 offset) in /home/tcj/src/MBBSEmu/MBBSEmu/Memory/MemoryCore.cs:line 307
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer) in /home/tcj/src/MBBSEmu/MBBSEmu/HostProcess/ExecutionUnits/ExecutionUnit.cs:line 105
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer) in /home/tcj/src/MBBSEmu/MBBSEmu/Module/MBBSModule.cs:line 259
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread() in /home/tcj/src/MBBSEmu/MBBSEmu/HostProcess/MbbsHost.cs:line 300
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

### PR DESCRIPTION
**Pull request by enusbaum**
- Fixed `lastwd` and wrote Unit Tests
- Fixed `skpwrd` and wrote Unit Tests
- Refactored `sameto` and wrote Unit Tests

Fixes #207

### CODE REVIEW

File: MBBSEmu/HostProcess/ExportedModules/Majorbbs.cs [hunk 1]
```diff
@@ -6990,14 +6963,12 @@ private void lastwd()
         {
             var stringPointerBase = GetParameterPointer(0);
 
-            var stringToParse = Encoding.ASCII.GetString(Module.Memory.GetString(stringPointerBase));
+            var stringToParse = Encoding.ASCII.GetString(Module.Memory.GetString(stringPointerBase, stripNull: true));
 
-            if (!Module.Memory.TryGetVariablePointer("lastwd-buffer", out var lastwdBufferPointer))
-                lastwdBufferPointer = Module.Memory.AllocateVariable("lastwd-buffer", 0xFF);
+            var lastWordIndex = stringToParse.LastIndexOf(' ');
+            lastWordIndex++; //Start on next character after space
```
Comment (paladine) [inline MBBSEmu/HostProcess/ExportedModules/Majorbbs.cs:6969]: LastIndexOf could return -1 if not found, but I guess that's OK since the following increment will just move it back to 0?

**Review by paladine — CHANGES_REQUESTED** [review]

File: MBBSEmu/HostProcess/ExportedModules/Majorbbs.cs (hunk 1 above)
Comment (enusbaum) [reply MBBSEmu/HostProcess/ExportedModules/Majorbbs.cs:6969]: Correct -- That was the idea, where if it's not found it just returns a pointer to the beginning of the string (same pointer passed in)

**Review by paladine — APPROVED** [review]
